name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm i
        id: deps

      - name: Lint
        run: pnpm run lint
        if: ${{ !cancelled() && steps.deps.outcome == 'success' }}

      - name: Typecheck
        run: pnpm run typecheck
        if: ${{ !cancelled() && steps.deps.outcome == 'success' }}

      - name: Test
        run: pnpm run test:cov
        if: ${{ !cancelled() && steps.deps.outcome == 'success' }}
        id: test

      - name: Codecov
        uses: codecov/codecov-action@v4
        if: ${{ !cancelled() && steps.test.outcome == 'success' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
